<a href="<?php echo $this->url(['controller' => 'Memo', 'action' => 'new'], 'default', true) ?>">
    <button type="button">新規作成</button>
</a>
<br>
<?php print($this->escape($this->memos)); ?>
<table border="2">
  <tr>
    <th width="100">ID</th>
    <th width="200">title</th>
    <th width="200">body</th>
    <th width="200">edit</th>
    <th width="200">delete</th>
  </tr>
  <?php foreach ($this->memos as $memo) : ?>
  <tr>
    <td>
      <?php echo $this->escape($memo['id']); ?>
    </td>
    <td>
      <?php echo $this->escape($memo['title']); ?>
    </td>
    <td>
      <?php echo $this->escape($memo['body']); ?>
    </td>
    <td>
      編集ボタン(工事中)
    </td>
    <td>
      削除ボタン(工事中 )
    </td>
  </tr>
  <?php endforeach; ?>
</table>